coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true

ignore:
  - "test_*.py"
  - "tests/"
  - "venv/"
  - ".venv/"
  - "env/"
  - ".env/"
